In [2]:
import numpy as np
x = np.array([[1,2,3],[4,5,6],[1,2,5]]) 
y = np.linalg.inv(x) 
print (y) 
print (np.dot(x,y))

[[-2.16666667  0.66666667  0.5       ]
 [ 2.33333333 -0.33333333 -1.        ]
 [-0.5         0.          0.5       ]]
[[ 1.  0.  0.]
 [ 0.  1.  0.]
 [ 0.  0.  1.]]


In [4]:
import numpy as np
from numpy.linalg import inv
X= np.array([[1,850,5,25,3],[1,520,4,16,2],[1,580,3,40,4],[1,360,1,32,5]])
y= np.array([[780],[690],[320],[300]])
X_trans= X.transpose()
theta = np.linalg.inv(X.transpose().dot(X)).dot(X_trans).dot(y)
print(theta)

[[  2.05500000e+03]
 [  1.66992188e+00]
 [ -3.36250000e+02]
 [ -2.52343750e+01]
 [ -1.58750000e+02]]


In [5]:
theta[0] + 850*theta[1] + 5*theta[2] + 25*theta[3] + 3*theta[4]

array([ 686.07421875])