In [1]:
import torch
import torch.nn as nn
import torch.nn.functional as func

class LogisticModel(nn.Module):
    def __init__(self, in_dim, out_dim):
        super(LogisticModel, self).__init__()
        self.linear = nn.Linear(in_dim, out_dim)
        
    def forward(self,x):
        out = func.sigmoid(self.linear(x))
        return out
in_dim, out_dim =1,1    
model = LogisticModel(1, 1)

In [2]:
criterion = torch.nn.BCELoss(size_average=True)
optimiser =  torch.optim.SGD(model.parameters(), lr =0.01)

In [3]:
x_train = torch.tensor([[1.6],[2.1],[1.3],[4.8],[3.5]], dtype=torch.float).reshape(-1,1)
y_train = torch.tensor([[0],[0],[0],[1],[1]], dtype=torch.float).reshape(-1,1) 

In [4]:
epochs = 1000 
for epoch in range(epochs):
    inputs, labels = x_train, y_train   
    out = model(inputs)    
    optimiser.zero_grad()    
    loss = criterion(out, labels)    
    loss.backward()    
    optimiser.step()
    predicted = model.forward(x_train)    
    print('epoch{}, loss {}'.format(epoch, loss.item()))

epoch0, loss 1.6305288076400757
epoch1, loss 1.6069027185440063
epoch2, loss 1.5834498405456543
epoch3, loss 1.5601754188537598
epoch4, loss 1.5370850563049316
epoch5, loss 1.5141843557357788
epoch6, loss 1.4914792776107788
epoch7, loss 1.4689756631851196
epoch8, loss 1.4466791152954102
epoch9, loss 1.4245960712432861
epoch10, loss 1.4027328491210938
epoch11, loss 1.3810956478118896
epoch12, loss 1.35969078540802
epoch13, loss 1.3385248184204102
epoch14, loss 1.3176043033599854
epoch15, loss 1.2969356775283813
epoch16, loss 1.2765257358551025
epoch17, loss 1.2563809156417847
epoch18, loss 1.2365080118179321
epoch19, loss 1.2169134616851807
epoch20, loss 1.197603702545166
epoch21, loss 1.178585410118103
epoch22, loss 1.1598647832870483
epoch23, loss 1.1414480209350586
epoch24, loss 1.1233413219451904
epoch25, loss 1.1055504083633423
epoch26, loss 1.0880807638168335
epoch27, loss 1.0709381103515625
epoch28, loss 1.0541274547576904
epoch29, loss 1.0376534461975098
epoch30, loss 1.02152085

epoch439, loss 0.48141899704933167
epoch440, loss 0.48121005296707153
epoch441, loss 0.4810013175010681
epoch442, loss 0.48079270124435425
epoch443, loss 0.4805842936038971
epoch444, loss 0.48037606477737427
epoch445, loss 0.480167955160141
epoch446, loss 0.47996005415916443
epoch447, loss 0.4797523021697998
epoch448, loss 0.4795447289943695
epoch449, loss 0.47933727502822876
epoch450, loss 0.4791300296783447
epoch451, loss 0.47892293334007263
epoch452, loss 0.47871604561805725
epoch453, loss 0.4785092771053314
epoch454, loss 0.47830265760421753
epoch455, loss 0.4780963063240051
epoch456, loss 0.4778900146484375
epoch457, loss 0.4776838719844818
epoch458, loss 0.4774779677391052
epoch459, loss 0.47727227210998535
epoch460, loss 0.47706660628318787
epoch461, loss 0.4768611490726471
epoch462, loss 0.47665587067604065
epoch463, loss 0.47645077109336853
epoch464, loss 0.47624582052230835
epoch465, loss 0.4760410189628601
epoch466, loss 0.4758364260196686
epoch467, loss 0.4756319522857666
e

epoch887, loss 0.4023546576499939
epoch888, loss 0.40220627188682556
epoch889, loss 0.40205803513526917
epoch890, loss 0.40190988779067993
epoch891, loss 0.40176185965538025
epoch892, loss 0.40161386132240295
epoch893, loss 0.40146604180336
epoch894, loss 0.4013182520866394
epoch895, loss 0.40117067098617554
epoch896, loss 0.4010232090950012
epoch897, loss 0.4008758068084717
epoch898, loss 0.4007285237312317
epoch899, loss 0.4005813002586365
epoch900, loss 0.4004341959953308
epoch901, loss 0.4002872407436371
epoch902, loss 0.4001403748989105
epoch903, loss 0.3999935984611511
epoch904, loss 0.39984697103500366
epoch905, loss 0.3997003436088562
epoch906, loss 0.39955395460128784
epoch907, loss 0.3994075655937195
epoch908, loss 0.39926132559776306
epoch909, loss 0.3991152048110962
epoch910, loss 0.39896923303604126
epoch911, loss 0.39882326126098633
epoch912, loss 0.3986774682998657
epoch913, loss 0.3985317349433899
epoch914, loss 0.3983860909938812
epoch915, loss 0.3982405960559845
epoch

In [5]:
print(model.state_dict())


OrderedDict([('linear.weight', tensor([[ 0.6929]])), ('linear.bias', tensor([-1.7570]))])


In [6]:
test=torch.tensor([[0.1],[1.5],[2.3],[3.0],[6.4]])
results = model(test)
for result in results:
    if result <= 0.5:
        print(result,'false')
    else: print(result, 'true')

tensor([ 0.1561]) false
tensor([ 0.3279]) false
tensor([ 0.4592]) false
tensor([ 0.5797]) true
tensor([ 0.9357]) true


In [9]:
nn.Threshold(xin,0)

Threshold(
  threshold=tensor([-3.0000, -2.7895, -2.5789, -2.3684, -2.1579, -1.9474, -1.7368,
          -1.5263, -1.3158, -1.1053, -0.8947, -0.6842, -0.4737, -0.2632,
          -0.0526,  0.1579,  0.3684,  0.5789,  0.7895,  1.0000]), value=0
)